language: java
before_install:
  - cp src/main/resources/application-template.properties src/main/resources/application.properties
deploy:
  provider: heroku
  api_key:
    secure: "1539ff7e-7eb0-478b-babb-0d8ac6343d22"
